CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_role_id ON users(role_id);
CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone);
CREATE INDEX IF NOT EXISTS idx_customers_customer_code ON customers(customer_code);
CREATE INDEX IF NOT EXISTS idx_employees_phone ON employees(phone);
CREATE INDEX IF NOT EXISTS idx_accounts_type_id ON accounts(type_id);
CREATE INDEX IF NOT EXISTS idx_accounts_short_name ON accounts(short_name);
CREATE INDEX IF NOT EXISTS idx_inventory_lots_lot_no ON inventory_lots(lot_no);
CREATE INDEX IF NOT EXISTS idx_inventory_lots_status ON inventory_lots(status);
CREATE INDEX IF NOT EXISTS idx_inventory_lots_item_type ON inventory_lots(item_type);
CREATE INDEX IF NOT EXISTS idx_purchases_supplier_date ON purchases(supplier_account_id, purchase_date);
CREATE INDEX IF NOT EXISTS idx_purchase_items_purchase_id ON purchase_items(purchase_id);
CREATE INDEX IF NOT EXISTS idx_sales_orders_customer_date ON sales_orders(customer_id, order_date);
CREATE INDEX IF NOT EXISTS idx_sales_orders_status ON sales_orders(status);
CREATE INDEX IF NOT EXISTS idx_sales_order_items_order_id ON sales_order_items(sales_order_id);
CREATE INDEX IF NOT EXISTS idx_sales_order_items_lot_id ON sales_order_items(lot_id);
CREATE INDEX IF NOT EXISTS idx_sales_order_items_status ON sales_order_items(item_status);
CREATE INDEX IF NOT EXISTS idx_payments_order_item ON payments(sales_order_id, sales_order_item_id);
CREATE INDEX IF NOT EXISTS idx_payments_account_date ON payments(account_id, payment_date);
CREATE INDEX IF NOT EXISTS idx_expenses_date_account ON expenses(expense_date, account_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_table_record ON audit_logs(table_name, record_id);
